name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Check if requirements.txt exists
      run: test -f requirements.txt || echo "requirements.txt not found"

    - name: Install dependencies
      if: success() && steps.existsCheck.outputs['file-found'] == 'true'
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s $GITHUB_WORKSPACE/Open_Source -p '*_test.py'
